name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build game
      run: |
        chmod +x compile.sh
        ./compile.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: plumino2-universal
        path: p2.love

