name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Zip the game's folder
      run: zip -r p2.love . -x "README.md .gitignore .git"
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: plumino2.love
        path: p2.love

